name: "kubewarden-check-artifacthub"
description: "Push artifacthub files to artifacthub branch"
branding:
  icon: "package"
  color: "blue"
inputs:
  policy-working-dir:
    description: "working directory of the policy. Useful for repos with policies in folders"
    required: false
    type: string
    default: .
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Push up-to-date artifacthub-pkg.yml
      shell: bash
      run: |
        git config user.name "Update artifacthub branch"
        git config user.email github-actions@github.com

        git checkout artifacthub || git checkout --orphan artifacthub
        git reset HEAD -- .

        if [ ${{ inputs.policy-working-dir }} != '.' ]; then
          # we need to replicate the policy-working-dir structure,
          # see https://artifacthub.io/docs/topics/repositories/kubewarden-policies
          #   path/to/packages
          #   ├── artifacthub-repo.yml
          #   └── policies/<policy name>
          #       ├── README.md
          #       └── artifacthub-pkg.yml
          git add artifacthub-repo.yml
          git add ${{ inputs.policy-working-dir }}/artifacthub-pkg.yml
          git add ${{ inputs.policy-working-dir }}/README.md # used if artifacthub-pkg.yml.readme is missing
          VERSION=$(sed --posix -n 's,^version: \(.*\),\1,p' ${{ inputs.policy-working-dir}}/artifacthub-pkg.yml)
          git commit -m "Update Artifact Hub files, version $VERSION"
        else 
          # we put everything flat:
          #   path/to/packages
          #   ├── artifacthub-repo.yml
          #   └── artifacthub-pkg.yml
          git add artifacthub-pkg.yml
          git add artifacthub-repo.yml
          git add README.md # used if artifacthub-pkg.yml.readme is missing
          VERSION=$(sed --posix -n 's,^version: \(.*\),\1,p' artifacthub-pkg.yml)
          git commit -m "Update Artifact Hub files, version $VERSION"
        fi

        git push --force origin artifacthub
