name: "kubewarden-check-artifacthub"
description: "Push artifacthub files to artifacthub branch"
branding:
  icon: "package"
  color: "blue"
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Check that artifacthub-pkg.yml is up-to-date
      shell: bash
      run: |
        git config user.name "Update artifacthub branch"
        git config user.email github-actions@github.com

        git checkout artifacthub || git checkout --orphan artifacthub
        git reset HEAD -- .
        git add artifacthub-pkg.yml
        git add artifacthub-repo.yml
        git add README.md # used if artifacthub-pkg.yml.readme is missing
        VERSION=$(sed --posix -n 's,^version: \(.*\),\1,p' artifacthub-pkg.yml)
        git commit -m "Update Artifact Hub files, version $VERSION"
        git push --force origin artifacthub
