name: 'tarpaulin-installer'
description: 'Installs latest tarpaulin and includes it inside of PATH'
branding:
  icon: 'package'
  color: 'blue'
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        #!/bin/bash
        set -e

        INSTALL_DIR=$HOME/.tarpaulin
        LATEST_RELEASE=$(curl -s https://api.github.com/repos/xd009642/tarpaulin/releases/latest | jq -r '.tag_name')

        mkdir -p $INSTALL_DIR

        curl -sL https://github.com/xd009642/tarpaulin/releases/download/$LATEST_RELEASE/cargo-tarpaulin-x86_64-unknown-linux-musl.tar.gz -o $INSTALL_DIR/tarpaulin.tar.gz
        tar xvf $INSTALL_DIR/tarpaulin.tar.gz -C $INSTALL_DIR
        rm $INSTALL_DIR/tarpaulin.tar.gz

        echo $INSTALL_DIR >> $GITHUB_PATH
