name: Build and release a Kubewarden policy written in Rego

on:
  workflow_call:
    inputs:
      oci-target:
        type: string
        required: true
      artifacthub:
        description: "check artifacthub-pkg.yml for submission to ArtifactHub"
        required: false
        type: boolean
        default: true
      policy-working-dir:
        description: "working directory of the policy. Useful for repos with policies in folders"
        required: false
        type: string
        default: .
      policy-version:
        description: |
          Release version of the policy, without 'v' prefix. Optional.
          Defaults to extracting the version from tag if tag present.
          E.g: tag "v0.1.0", policy-version=0.1.0
        required: false
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        uses: kubewarden/github-actions/policy-gh-action-dependencies@v3.3.5
      - uses: actions/checkout@v4
        with:
          # until https://github.com/actions/checkout/pull/579 is released
          fetch-depth: 0
      - id: calculate-version
        shell: bash
        run: |
          if [ "${{ inputs.policy-version }}" != "" ];then 
            # If present, it means we are dealing with tags in the form of PolicyName/v0.1.0
            # Transform the passed policy-version=0.1.0 into version=v0.1.0
            echo "version=${{ inputs.policy-version }}" >> $GITHUB_OUTPUT
          else
            # We are dealing with normal tags. Use the full tag, after cutting the `v` prefix
            echo "version=$(git describe --tags --abbrev=0 | cut -c2-)" >> $GITHUB_OUTPUT
          fi
      - name: Check that artifacthub-pkg.yml is up-to-date
        # skip when releasing :latest from main, versions will not match
        if: ${{ inputs.artifacthub && ( ! startsWith(github.ref, 'refs/heads/') }}
        uses: viccuad/github-actions/check-artifacthub@main
        with:
          version: ${{ steps.calculate-version.outputs.version }}
          policy-working-dir: ${{ inputs.policy-working-dir }}
      - name: Install opa
        uses: viccuad/github-actions/opa-installer@main
      - uses: actions/checkout@v4
      - name: Build policy
        working-directory: ${{ inputs.policy-working-dir }}
        shell: bash
        run: |
          make policy.wasm
      - name: Annotate policy
        working-directory: ${{ inputs.policy-working-dir }}
        shell: bash
        run: |
          make annotated-policy.wasm
      - name: Run e2e tests
        working-directory: ${{ inputs.policy-working-dir }}
        shell: bash
        run: |
          make e2e-tests
      - name: Release
        uses: viccuad/github-actions/policy-release@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          oci-target: ${{ inputs.oci-target }}
          policy-working-dir: ${{ inputs.policy-working-dir }}
          policy-version: ${{ steps.calculate-version.outputs.version }}
  push-artifacthub:
    # skip when releasing :latest from main, versions will not match
    if: ${{ inputs.artifacthub && ( ! startsWith(github.ref, 'refs/heads/') ) }}
    needs: release
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Push artifacthub files to artifacthub branch
        uses: viccuad/github-actions/push-artifacthub@main
        with:
          policy-working-dir: ${{ inputs.policy-working-dir }}
