name: Tests and linters

on:
  workflow_call:
    inputs:
      artifacthub:
        description: "check artifacthub-pkg.yml for submission to ArtifactHub"
        required: false
        type: boolean
        default: true
      policy-working-dir:
        description: "working directory of the policy. Useful for repos with policies in folders"
        required: false
        type: string
        default: .
      policy-version:
        description: "release version of the policy. Useful for repos with policies in folders, and only on release jobs"
        required: false
        type: string
    secrets: {}

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install opa
        uses: viccuad/github-actions/opa-installer@main
      - name: Run unit tests
        working-directory: ${{ inputs.policy-working-dir }}
        run: make test
  check-artifacthub:
    # construct updated artifacthub-pkg.yml and check it contains the correct values
    if: ${{ inputs.artifacthub }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # until https://github.com/actions/checkout/pull/579 is released
          fetch-depth: 0
      - name: Install kwctl
        uses: kubewarden/github-actions/kwctl-installer@v3.3.5
      - id: calculate-version
        shell: bash
        run: |
          if [ "${{ inputs.policy-version }}" != "" ];then 
            echo "version=${{ inputs.policy-version }}" >> $GITHUB_OUTPUT
          else
            echo "version=$(git describe --tags --abbrev=0 | cut -c2-)" >> $GITHUB_OUTPUT
          fi
      - name: Check that artifacthub-pkg.yml is up-to-date
        # only makes sense to run this check if artifacthub-pkg.yml has been
        # updated for an upcoming release.
        uses: viccuad/github-actions/check-artifacthub@main
        with:
          version: ${{ steps.calculate-version.outputs.version }}
          check_version: false # must match a git tag that hasn't been created yet, so let's ignore until then
          policy-working-dir: ${{ inputs.policy-working-dir }}
